name: my first wf
on: 
    push:
    workflow_dispatch:
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: welcome msg
              run: echo "hello data eng"

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt
    test_job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - name: Test File exists
              run: grep -i "dragon" dragon.txt
            
    deploy-job:
        needs: [test_job, first-job]
        runs-on: ubuntu-latest
        steps:
            - name: Read File
              run: cat dragon.txt

            - name: checkout repo files
              run: ls
 