name: my first wf
on: 
    push:
    workflow_dispatch:
jobs:
    hamada:
        runs-on: ubuntu-latest
        steps:
            - name: welcome msg
              run: echo "hello data eng"
            - name: list files
              run: ls
 