name: my first wf
on: 
    push:
    workflow_dispatch:
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.7

            - name: welcome msg
              run: echo "hello data eng"

            - name: install cowsay program
              run: sudo apt-get install cowsay -y

            - name: execute cowsay cmd
              run: cowsay -f dragon "Run for cover, iam a Dragon....RAWR" >> dragon.txt

            - uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt
    test_job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:

            - uses: actions/download-artifact@v4
              with:
               path: dragon-file

            - name: Test File exists
              run: grep -i dragon-file
            
    deploy-job:
        needs: [test_job, first-job]
        runs-on: ubuntu-latest
        steps:

            - uses: actions/download-artifact@v4
              with:
               path: dragon-file
            
            - name: unzip dir
              run: unzip dragon-file

            - name: Read File
              run: cat dragon.txt

            - name: checkout repo files
              run: ls
 